[versions]
agp = "8.7.0-alpha03"
androidServicemanagerVersion = "1.0.5"
apkzlib = "8.5.1"
chaquopyNumpy = "latest-version"
chaquopy = "latest-version"
collection = "1.2.0"
commonmark = "0.22.0"
commonsCompress = "1.26.2"
coreKtxVersion = "1.13.0"
fastjson = "2.0.52"
githubStreamzip = "v1.0.6"
gradleVersion = "7.4.2"
gsonVersion = "2.10.1"
guava = "33.3.0-jre"
json = "20240303"
jsr305 = "3.0.2"
jythonStandalone = "2.7.3"
kotlin = "2.0.0-RC3"
coreKtx = "1.10.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
activity = "1.9.1"
luajJse = "3.0.2"
luajJseVersion = "3.0.1"
material = "1.12.0"
constraintlayout = "2.1.4"
lifecycleLivedataKtx = "2.6.1"
lifecycleViewmodelKtx = "2.6.1"
mmkvStatic = "1.2.10"
navigationFragmentKtx = "2.6.0"
navigationUiKtx = "2.6.0"
cardviewV7 = "28.0.0"
python = "15.0.1"
plugin = "15.0.1"
shadowhook = "1.0.10"
uiAndroid = "1.6.8"
zip4j = "2.11.5"
firebaseCrashlyticsBuildtools = "3.0.2"

[libraries]
androidx-collection = { module = "androidx.collection:collection", version.ref = "collection" }
androidx-core-ktx-v1130 = { module = "androidx.core:core-ktx", version.ref = "coreKtxVersion" }
androidzip = { module = "com.github.buggysofts-com:AndroidZip", version.ref = "githubStreamzip" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version = "1.12.0-alpha01" }
apkzlib = { module = "com.android.tools.build:apkzlib", version.ref = "apkzlib" }
build-gradle = { module = "com.android.tools.build:gradle", version.ref = "gradleVersion" }
chaquopy = { module = "com.chaquo.chaquopy:chaquopy", version.ref = "chaquopy" }
chaquopy-numpy = { module = "com.chaquo.chaquopy:chaquopy-numpy", version.ref = "chaquopyNumpy" }
commonmark = { module = "org.commonmark:commonmark", version.ref = "commonmark" }
commons-compress = { module = "org.apache.commons:commons-compress", version.ref = "commonsCompress" }
fastjson = { module = "com.alibaba:fastjson", version.ref = "fastjson" }
github-streamzip = { module = "com.github.buggysofts-com:StreamZip", version.ref = "githubStreamzip" }
google-gson = { module = "com.google.code.gson:gson", version.ref = "gsonVersion" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
json = { module = "org.json:json", version.ref = "json" }
jsr305 = { module = "com.google.code.findbugs:jsr305", version.ref = "jsr305" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
jython-standalone = { module = "org.python:jython-standalone", version.ref = "jythonStandalone" }
luaj-jse = { module = "org.luaj:luaj-jse", version.ref = "luajJse" }
luaj-jse-v301 = { module = "org.luaj:luaj-jse", version.ref = "luajJseVersion" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }
mmkv-static = { module = "com.tencent:mmkv-static", version = "1.3.5" }
cardview-v7 = { group = "com.android.support", name = "cardview-v7", version.ref = "cardviewV7" }
plugin = { module = "org.chaquopy:plugin", version.ref = "plugin" }
python = { module = "org.chaquopy:python", version.ref = "python" }
shadowhook = { module = "com.bytedance.android:shadowhook", version.ref = "shadowhook" }
support-android-servicemanager = { module = "com.limpoxe.support:android-servicemanager", version.ref = "androidServicemanagerVersion" }
androidx-ui-android = { group = "androidx.compose.ui", name = "ui-android", version.ref = "uiAndroid" }
zip4j = { module = "net.lingala.zip4j:zip4j", version.ref = "zip4j" }
firebase-crashlytics-buildtools = { group = "com.google.firebase", name = "firebase-crashlytics-buildtools", version.ref = "firebaseCrashlyticsBuildtools" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }

