[versions]
agp = "8.5.0-alpha06"
androidServicemanagerVersion = "1.0.5"
chaquopyNumpy = "latest-version"
chaquopy = "latest-version"
collection = "1.2.0"
githubStreamzip = "v1.0.6"
gradleVersion = "7.4.2"
gsonVersion = "2.10.1"
jythonStandalone = "2.7.3"
kotlin = "1.9.0"
coreKtx = "1.10.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
luajJse = "3.0.2"
luajJseVersion = "3.0.1"
material = "1.10.0"
constraintlayout = "2.1.4"
lifecycleLivedataKtx = "2.6.1"
lifecycleViewmodelKtx = "2.6.1"
mmkvStatic = "1.2.10"
navigationFragmentKtx = "2.6.0"
navigationUiKtx = "2.6.0"
cardviewV7 = "28.0.0"
python = "15.0.1"
plugin = "15.0.1"
uiAndroid = "1.6.8"

[libraries]
androidx-collection = { module = "androidx.collection:collection", version.ref = "collection" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidzip = { module = "com.github.buggysofts-com:AndroidZip", version.ref = "githubStreamzip" }
build-gradle = { module = "com.android.tools.build:gradle", version.ref = "gradleVersion" }
chaquopy = { module = "com.chaquo.chaquopy:chaquopy", version.ref = "chaquopy" }
chaquopy-numpy = { module = "com.chaquo.chaquopy:chaquopy-numpy", version.ref = "chaquopyNumpy" }
github-streamzip = { module = "com.github.buggysofts-com:StreamZip", version.ref = "githubStreamzip" }
google-gson = { module = "com.google.code.gson:gson", version.ref = "gsonVersion" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
jython-standalone = { module = "org.python:jython-standalone", version.ref = "jythonStandalone" }
luaj-jse = { module = "org.luaj:luaj-jse", version.ref = "luajJse" }
luaj-jse-v301 = { module = "org.luaj:luaj-jse", version.ref = "luajJseVersion" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }
mmkv-static = { module = "com.tencent:mmkv-static", version = "1.3.5" }
cardview-v7 = { group = "com.android.support", name = "cardview-v7", version.ref = "cardviewV7" }
plugin = { module = "org.chaquopy:plugin", version.ref = "plugin" }
python = { module = "org.chaquopy:python", version.ref = "python" }
support-android-servicemanager = { module = "com.limpoxe.support:android-servicemanager", version.ref = "androidServicemanagerVersion" }
androidx-ui-android = { group = "androidx.compose.ui", name = "ui-android", version.ref = "uiAndroid" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }

