package eternal.future.tefmodloader.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

object Pink: ThemeData() {
    override val lightScheme = lightColorScheme(
        primary = Color(0xFF8D4959),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFFFD9DF),
        onPrimaryContainer = Color(0xFF713342),
        secondary = Color(0xFF75565C),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFFFD9DF),
        onSecondaryContainer = Color(0xFF5C3F44),
        tertiary = Color(0xFF7A5732),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFFFDCBC),
        onTertiaryContainer = Color(0xFF5F401D),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF93000A),
        background = Color(0xFFFFF8F7),
        onBackground = Color(0xFF22191B),
        surface = Color(0xFFFFF8F7),
        onSurface = Color(0xFF22191B),
        surfaceVariant = Color(0xFFF3DDE0),
        onSurfaceVariant = Color(0xFF524345),
        outline = Color(0xFF847375),
        outlineVariant = Color(0xFFD6C2C4),
        scrim = Color(0xFF000000),
        inverseSurface = Color(0xFF382E2F),
        inverseOnSurface = Color(0xFFFEEDEE),
        inversePrimary = Color(0xFFFFB1C0),
        surfaceDim = Color(0xFFE7D6D8),
        surfaceBright = Color(0xFFFFF8F7),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFFFF0F1),
        surfaceContainer = Color(0xFFFBEAEB),
        surfaceContainerHigh = Color(0xFFF5E4E6),
        surfaceContainerHighest = Color(0xFFEFDEE0),
    )

    override val darkScheme = darkColorScheme(
        primary = Color(0xFFFFB1C0),
        onPrimary = Color(0xFF551D2C),
        primaryContainer = Color(0xFF713342),
        onPrimaryContainer = Color(0xFFFFD9DF),
        secondary = Color(0xFFE4BDC3),
        onSecondary = Color(0xFF43292E),
        secondaryContainer = Color(0xFF5C3F44),
        onSecondaryContainer = Color(0xFFFFD9DF),
        tertiary = Color(0xFFECBE90),
        onTertiary = Color(0xFF462A08),
        tertiaryContainer = Color(0xFF5F401D),
        onTertiaryContainer = Color(0xFFFFDCBC),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        background = Color(0xFF191113),
        onBackground = Color(0xFFEFDEE0),
        surface = Color(0xFF191113),
        onSurface = Color(0xFFEFDEE0),
        surfaceVariant = Color(0xFF524345),
        onSurfaceVariant = Color(0xFFD6C2C4),
        outline = Color(0xFF9F8C8F),
        outlineVariant = Color(0xFF524345),
        scrim = Color(0xFF000000),
        inverseSurface = Color(0xFFEFDEE0),
        inverseOnSurface = Color(0xFF382E2F),
        inversePrimary = Color(0xFF8D4959),
        surfaceDim = Color(0xFF191113),
        surfaceBright = Color(0xFF413738),
        surfaceContainerLowest = Color(0xFF140C0D),
        surfaceContainerLow = Color(0xFF22191B),
        surfaceContainer = Color(0xFF261D1F),
        surfaceContainerHigh = Color(0xFF312829),
        surfaceContainerHighest = Color(0xFF3C3234),
    )
}